"""Initial schema: 9 tables, 7 PostgreSQL enums, all relationships.

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-09-08 12:00:00.000000

Full schema for Security Signals:
- source (RSS feeds, APIs, web crawlers, databases)
- user (reviewers, admins)
- article (source articles, news, security bulletins)
- security_event (CVEs, threats, incidents)
- event_article_mapping (M2M: SecurityEvent ↔ Article)
- signal (AI-generated insight + secure design principle)
- signal_category (taxonomy classification)
- evidence (supporting quotes + audit trail)
- audit_log (all mutations)

All UUIDs generated by PostgreSQL (gen_random_uuid).
All timestamps timezone-aware UTC.
Foreign keys: RESTRICT or CASCADE or SET NULL as specified.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM, JSON, UUID


# Revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create initial schema with all 9 tables and 7 enum types."""
    
    # =========================================================================
    # Create all PostgreSQL ENUM types
    # =========================================================================
    
    source_type_enum = ENUM('RSS', 'API', 'WEB', 'DATABASE', name='source_type_enum')
    source_type_enum.create(op.get_bind())
    
    event_type_enum = ENUM('VULNERABILITY', 'BREACH', 'THREAT_INTELLIGENCE', 'PATCH_AVAILABLE', name='event_type_enum')
    event_type_enum.create(op.get_bind())
    
    event_severity_enum = ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='event_severity_enum')
    event_severity_enum.create(op.get_bind())
    
    signal_status_enum = ENUM('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', name='signal_status_enum')
    signal_status_enum.create(op.get_bind())
    
    security_category_enum = ENUM(
        'VULNERABILITY', 'CLOUD_SECURITY', 'IAM', 'APP_API', 'SUPPLY_CHAIN',
        'DATA_PRIVACY', 'RANSOMWARE', 'THREAT_INTEL', 'AI_SECURITY', 'INFRASTRUCTURE',
        name='security_category_enum'
    )
    security_category_enum.create(op.get_bind())
    
    ai_security_subcategory_enum = ENUM(
        'LLM_VULNERABILITY', 'AGENT_ABUSE', 'AI_DATA_LEAKAGE', 'MODEL_POISONING',
        'AI_SUPPLY_CHAIN', 'AI_INFRASTRUCTURE', 'AI_ENABLED_ATTACKS', 'MISALIGNED_AI_PERMISSIONS',
        name='ai_security_subcategory_enum'
    )
    ai_security_subcategory_enum.create(op.get_bind())
    
    user_role_enum = ENUM('ADMIN', 'REVIEWER', 'VIEWER', name='user_role_enum')
    user_role_enum.create(op.get_bind())
    
    assignment_method_enum = ENUM('AI', 'MANUAL', name='assignment_method_enum')
    assignment_method_enum.create(op.get_bind())
    
    # =========================================================================
    # Create all tables
    # Note: create_type=False prevents SQLAlchemy from re-creating ENUM types
    # =========================================================================
    
    # source: RSS feeds, APIs, web crawlers, databases
    op.create_table(
        'source',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('name', sa.String(255), nullable=False, unique=True),
        sa.Column('source_type', ENUM('RSS', 'API', 'WEB', 'DATABASE', name='source_type_enum', create_type=False), nullable=False, server_default='RSS'),
        sa.Column('url', sa.String(2048), nullable=False),
        sa.Column('config', JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    op.create_index('idx_source_name', 'source', ['name'])
    
    # user: Reviewers and admins who review and approve signals
    op.create_table(
        'user',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('username', sa.String(255), nullable=False, unique=True),
        sa.Column('email', sa.String(255), nullable=False, unique=True),
        sa.Column('role', ENUM('ADMIN', 'REVIEWER', 'VIEWER', name='user_role_enum', create_type=False), nullable=False, server_default='VIEWER'),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    op.create_index('idx_user_username', 'user', ['username'])
    op.create_index('idx_user_email', 'user', ['email'])
    
    # article: News articles, blog posts, security bulletins from sources
    op.create_table(
        'article',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('source_id', UUID(as_uuid=True), nullable=False),
        sa.Column('url', sa.String(2048), nullable=False, unique=True),
        sa.Column('title', sa.String(1024), nullable=False),
        sa.Column('content_hash', sa.String(64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='fk_article_source_id', ondelete='RESTRICT'),
    )
    op.create_index('idx_article_source_id', 'article', ['source_id'])
    op.create_index('idx_article_url', 'article', ['url'])
    op.create_index('idx_article_created_at', 'article', ['created_at'])
    
    # security_event: CVEs, threat intelligence, incidents
    op.create_table(
        'security_event',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('name', sa.String(255), nullable=False, unique=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('event_type', ENUM('VULNERABILITY', 'BREACH', 'THREAT_INTELLIGENCE', 'PATCH_AVAILABLE', name='event_type_enum', create_type=False), nullable=False, server_default='VULNERABILITY'),
        sa.Column('severity', ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='event_severity_enum', create_type=False), nullable=False, server_default='MEDIUM'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    op.create_index('idx_security_event_name', 'security_event', ['name'])
    op.create_index('idx_security_event_event_type', 'security_event', ['event_type'])
    op.create_index('idx_security_event_severity', 'security_event', ['severity'])
    op.create_index('idx_security_event_created_at', 'security_event', ['created_at'])
    
    # event_article_mapping: M2M between SecurityEvent and Article
    op.create_table(
        'event_article_mapping',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('event_id', UUID(as_uuid=True), nullable=False),
        sa.Column('article_id', UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['event_id'], ['security_event.id'], name='fk_event_article_mapping_event_id', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='fk_event_article_mapping_article_id', ondelete='CASCADE'),
        sa.UniqueConstraint('event_id', 'article_id', name='uq_event_article_mapping_event_article'),
    )
    op.create_index('idx_event_article_mapping_event_id', 'event_article_mapping', ['event_id'])
    op.create_index('idx_event_article_mapping_article_id', 'event_article_mapping', ['article_id'])
    
    # signal: AI-generated insight + secure design principle
    op.create_table(
        'signal',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('event_id', UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('security_impact', sa.Text(), nullable=False),
        sa.Column('principle', sa.Text(), nullable=False),
        sa.Column('recommended_action', sa.Text(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('status', ENUM('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'PUBLISHED', name='signal_status_enum', create_type=False), nullable=False, server_default='DRAFT'),
        sa.Column('reviewed_by', UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['event_id'], ['security_event.id'], name='fk_signal_event_id', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name='fk_signal_reviewed_by', ondelete='SET NULL'),
    )
    op.create_index('idx_signal_event_id', 'signal', ['event_id'])
    op.create_index('idx_signal_status', 'signal', ['status'])
    op.create_index('idx_signal_reviewed_by', 'signal', ['reviewed_by'])
    op.create_index('idx_signal_created_at', 'signal', ['created_at'])
    
    # signal_category: Taxonomy classification (category + optional AI_SECURITY subcategory)
    op.create_table(
        'signal_category',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('signal_id', UUID(as_uuid=True), nullable=False),
        sa.Column('category', ENUM('VULNERABILITY', 'CLOUD_SECURITY', 'IAM', 'APP_API', 'SUPPLY_CHAIN', 'DATA_PRIVACY', 'RANSOMWARE', 'THREAT_INTEL', 'AI_SECURITY', 'INFRASTRUCTURE', name='security_category_enum', create_type=False), nullable=False),
        sa.Column('subcategory', ENUM('LLM_VULNERABILITY', 'AGENT_ABUSE', 'AI_DATA_LEAKAGE', 'MODEL_POISONING', 'AI_SUPPLY_CHAIN', 'AI_INFRASTRUCTURE', 'AI_ENABLED_ATTACKS', 'MISALIGNED_AI_PERMISSIONS', name='ai_security_subcategory_enum', create_type=False), nullable=True),
        sa.Column('assigned_by', ENUM('AI', 'MANUAL', name='assignment_method_enum', create_type=False), nullable=False, server_default='AI'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], name='fk_signal_category_signal_id', ondelete='CASCADE'),
    )
    op.create_index('idx_signal_category_signal_id', 'signal_category', ['signal_id'])
    op.create_index('idx_signal_category_category', 'signal_category', ['category'])
    
    # evidence: Supporting quotes + audit trail (immutable at application layer)
    op.create_table(
        'evidence',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('signal_id', UUID(as_uuid=True), nullable=False),
        sa.Column('article_id', UUID(as_uuid=True), nullable=True),
        sa.Column('source_url', sa.String(2048), nullable=False),
        sa.Column('source_title', sa.String(1024), nullable=False),
        sa.Column('excerpt', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], name='fk_evidence_signal_id', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='fk_evidence_article_id', ondelete='SET NULL'),
    )
    op.create_index('idx_evidence_signal_id', 'evidence', ['signal_id'])
    op.create_index('idx_evidence_article_id', 'evidence', ['article_id'])
    op.create_index('idx_evidence_created_at', 'evidence', ['created_at'])
    
    # audit_log: All mutations (immutable at application layer)
    op.create_table(
        'audit_log',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, default=sa.func.gen_random_uuid()),
        sa.Column('user_id', UUID(as_uuid=True), nullable=True),
        sa.Column('entity_type', sa.String(255), nullable=False),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('changes', JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_audit_log_user_id', ondelete='SET NULL'),
    )
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'])
    op.create_index('idx_audit_log_entity_type', 'audit_log', ['entity_type'])
    op.create_index('idx_audit_log_entity_id', 'audit_log', ['entity_id'])
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'])


def downgrade() -> None:
    """Drop all tables and ENUM types."""
    
    # Drop tables in reverse dependency order
    op.drop_table('audit_log')
    op.drop_table('evidence')
    op.drop_table('signal_category')
    op.drop_table('signal')
    op.drop_table('event_article_mapping')
    op.drop_table('security_event')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('source')
    
    # Drop all ENUM types
    op.execute('DROP TYPE assignment_method_enum')
    op.execute('DROP TYPE user_role_enum')
    op.execute('DROP TYPE ai_security_subcategory_enum')
    op.execute('DROP TYPE security_category_enum')
    op.execute('DROP TYPE signal_status_enum')
    op.execute('DROP TYPE event_severity_enum')
    op.execute('DROP TYPE event_type_enum')
    op.execute('DROP TYPE source_type_enum')
